timetable_v3/api/urls.py
from django.urls import path

from api.views import TimeTableView, ReserveClassRoomView, ReserveGradeYearView, FacultyView, DepartmentView, \
    CourseTimeTableView, ReserveTeacherView

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

app_name = 'api'
schema_view = get_schema_view(
    openapi.Info(
        title="Manas TimeTable API documentation",
        default_version='v1',
        description="Manas TimeTable",
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('timetable/', TimeTableView.as_view(), name='timetable'),
    path('reserve/classroom/', ReserveClassRoomView.as_view(), name='reserve_classroom'),
    path('reserve/teacher/', ReserveTeacherView.as_view(), name='reserve_classroom'),
    path('reserve/grade_year/', ReserveGradeYearView.as_view(), name='reserve_classroom'),
    path('faculty/', FacultyView.as_view(), name='faculty_list'),
    path('deparment/', DepartmentView.as_view(), name='department_list'),
    path('course/', CourseTimeTableView.as_view(), name='course_detail'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='swagger'),
]

timetable_v3/secretariat/urls.py
from django.urls import path

from secretariat.views import ClassRoomTimeTableView, CustomLoginView, CustomLogoutView, ListClassRoomView, \
    CreateClassRoomView, \
    UpdateClassRoomView, DeleteClassRoomView, ListTeacherView, CreateTeacherView, UpdateTeacherView, DeleteTeacherView, \
    ListGradeYearView, CreateGradeYearView, UpdateGradeYearView, DeleteGradeYearView, ListCourseView, CreateCourseView, \
    UpdateCourseView, DeleteCourseView, ListCourseVsRoomView, DeleteCourseVsRoomView, UpdateCourseVsRoomView, \
    CreateCourseVsRoomView, UnusedCourseView

app_name = 'secretariat'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('timetable/', ClassRoomTimeTableView.as_view(), name='class_room_timetable'),
    path('classrooms/', ListClassRoomView.as_view(), name='list_class_room'),
    path('classroom/create/', CreateClassRoomView.as_view(), name='create_class_room'),
    path('classroom/update/<int:id>/', UpdateClassRoomView.as_view(), name='update_class_room'),
    path('classroom/delete/<int:id>/', DeleteClassRoomView.as_view(), name='delete_class_room'),
    path('teachers/', ListTeacherView.as_view(), name='list_teacher'),
    path('teacher/create/', CreateTeacherView.as_view(), name='create_teacher'),
    path('teacher/update/<int:id>/', UpdateTeacherView.as_view(), name='update_teacher'),
    path('teacher/delete/<int:id>/', DeleteTeacherView.as_view(), name='delete_teacher'),
    path('grade_years/', ListGradeYearView.as_view(), name='list_grade_year'),
    path('grade_year/create/', CreateGradeYearView.as_view(), name='create_grade_year'),
    path('grade_year/update/<int:id>/', UpdateGradeYearView.as_view(), name='update_grade_year'),
    path('grade_year/delete/<int:id>/', DeleteGradeYearView.as_view(), name='delete_grade_year'),
    path('courses/', ListCourseView.as_view(), name='list_course'),
    path('unused_courses/', UnusedCourseView.as_view(), name='list_unused_course'),
    path('course/create/', CreateCourseView.as_view(), name='create_course'),
    path('course/update/<int:id>/', UpdateCourseView.as_view(), name='update_course'),
    path('course/delete/<int:id>/', DeleteCourseView.as_view(), name='delete_course'),
    path('coursevsrooms/', ListCourseVsRoomView.as_view(), name='list_course_vs_room'),
    path('coursevsroom/create/', CreateCourseVsRoomView.as_view(), name='create_course_vs_room'),
    path('coursevsroom/update/<int:id>/', UpdateCourseVsRoomView.as_view(), name='update_course_vs_room'),
    path('coursevsroom/delete/<int:id>/', DeleteCourseVsRoomView.as_view(), name='delete_course_vs_room'),
]

timetable_v3/timetable_v3/urls.py
from django.contrib import admin
from django.urls import path,include
import debug_toolbar
from webapp import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('secretariat/', include('secretariat.urls', namespace='secretariat')),
    path('api/', include('api.urls', namespace='api')),
    path('__debug__/', include(debug_toolbar.urls)),
]

timetable_v3/secretariat/models.py
from django.db import models

# Create your models here.

timetable_v3/secretariat/views.py
import json

from django.db.models.expressions import RawSQL
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView
from django.views.generic.base import View
from django.urls import reverse

from secretariat.forms import ClassRoomForm, TeacherForm, GradeYearForm, CourseForm, CourseVsRoomForm
from webapp.models import ClassRoom, Teacher, GradeYear, Course, CourseVsRoom, Building, TimeTable, TimeDay, TimeHour, \
    TIMETABLE_RESERVED
from webapp.views import ListTimeTable
from django.db import models
from django.db.models import Count, F, Q, Sum, Subquery, Prefetch


class LoginRequiredMixin:
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('secretariat:login')
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class CustomLoginView(LoginView):
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse('secretariat:class_room_timetable')


class CustomLogoutView(LogoutView):
    next_page = 'secretariat:login'


class ClassRoomTimeTableView(LoginRequiredMixin, View):
    template_name = 'classroom/timetable.html'

    def get(self, request, *args, **kwargs):
        building_short_names = Building.objects.order_by('short_name')
        rooms = self.get_rooms()
        return render(request, self.template_name, context={'rooms': rooms,'building_short_names':building_short_names })

    def post(self, request, *args, **kwargs):

        building_short_names = Building.objects.order_by('short_name')
        room_id = self.request.POST.get('room', 0)
        room = get_object_or_404(ClassRoom, id=room_id)
        timetable = TimeTable.objects.select_related('classroom', 'classroom__building', 'course', 'course__teacher',
                                                     'course__type', 'course__department', 'course__department__faculty',
                                                     'classroom__building','time_day', 'time_hour' ).\
            filter(classroom=room).order_by('time_hour_id', 'time_day_id')
        unused_courses = Course.objects.select_related('teacher', 'department', 'type').annotate(used_count=Count('timetable', distinct=True, )).\
            annotate(max_used_count=F('practice_hours') + F('theory_hours'),)
        unused_courses = unused_courses.filter(rooms__classroom_id=room.id).distinct()
        reserved_classroom = ClassRoom.objects.prefetch_related(Prefetch('timetable_set',
                                                                         TimeTable.objects.select_related('classroom',
                                                                                                          'classroom__building',
                                                                                                          'course',
                                                                                                          'course__teacher',
                                                                                                          'course__type',
                                                                                                          'course__department',
                                                                                                          'course__department__faculty',
                                                                                                          'classroom__building',
                                                                                                          'time_day',
                                                                                                          'time_hour').filter(course__name=TIMETABLE_RESERVED))).get(
            name=TIMETABLE_RESERVED)
        for course in unused_courses:
            course.set_reserved_list(reserved_classroom.timetable_set.all())
        for table in timetable:
            if table.course:
                table.course.set_reserved_list(reserved_classroom.timetable_set.all())

        days, hours, index = TimeDay.objects.all().order_by('pk'), TimeHour.objects.all().order_by('pk'), 0
        result = [ListTimeTable(time_day_id=day.id, time_hour_id=hour.id) for hour in hours for day in days]
        for table in result:
            while index < len(timetable) and timetable[index].time_hour_id == table.time_hour_id and \
                    timetable[index].time_day_id == table.time_day_id:
                table.get_values(timetable[index], take_reserved=True)
                index += 1
        rooms = self.get_rooms()
        return render(request, self.template_name, context={'rooms': rooms, 'timetable': result,
                                                            'selected_room': room,'selected_building_short': room.building.short_name,
                                                            'days': days, 'hours': hours, 'building_short_names':building_short_names,
                                                            'unused_courses': unused_courses})

    def get_rooms(self):
        return ClassRoom.objects.select_related('building').exclude(name=TIMETABLE_RESERVED).order_by('building__short_name')


class ListClassRoomView(LoginRequiredMixin, ListView):
    template_name = 'classroom/list.html'
    context_object_name = 'classrooms'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ListClassRoomView, self).get_context_data(**kwargs)
        context['total_count'] = len(context['classrooms'])
        return context

    def get_queryset(self):
        return ClassRoom.objects.select_related('building', 'room_type', 'department').filter(user_id=self.request.user.id)


class CreateClassRoomView(LoginRequiredMixin, CreateView):
    form_class = ClassRoomForm
    template_name = 'classroom/create.html'

    def get_form_kwargs(self):
        kwargs = super(CreateClassRoomView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        return reverse('secretariat:list_class_room')


class UpdateClassRoomView(LoginRequiredMixin, UpdateView):
    form_class = ClassRoomForm
    template_name = 'classroom/update.html'

    def get_context_data(self, **kwargs):
        context = super(UpdateClassRoomView, self).get_context_data(**kwargs)
        context['reserved_timetable'] = self.object.list_reserved()
        return context

    def get_object(self, queryset=None):
        return get_object_or_404(ClassRoom, id=self.kwargs.get('id', 0))

    def get_form_kwargs(self):
        kwargs = super(UpdateClassRoomView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        return reverse('secretariat:list_class_room')


class DeleteClassRoomView(LoginRequiredMixin, DeleteView):
    template_name = 'partial/delete.html'

    def get_object(self, queryset=None):
        return get_object_or_404(ClassRoom, id=self.kwargs.get('id', 0))

    def get_success_url(self):
        return reverse('secretariat:list_class_room')


class ListTeacherView(LoginRequiredMixin, ListView):
    template_name = 'teacher/list.html'
    context_object_name = 'teachers'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ListTeacherView, self).get_context_data(**kwargs)
        context['total_count'] = len(context['teachers'])
        return context

    def get_queryset(self):
        return Teacher.objects.filter(user_id=self.request.user.id).order_by('name')


class CreateTeacherView(LoginRequiredMixin, CreateView):
    form_class = TeacherForm
    template_name = 'teacher/create.html'

    def get_form_kwargs(self):
        kwargs = super(CreateTeacherView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        return reverse('secretariat:list_teacher')


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    form_class = TeacherForm
    template_name = 'teacher/update.html'

    def get_context_data(self, **kwargs):
        context = super(UpdateTeacherView, self).get_context_data(**kwargs)
        context['reserved_timetable'] = self.object.list_reserved()
        return context

    def get_object(self, queryset=None):
        return get_object_or_404(Teacher, id=self.kwargs.get('id', 0))

    def get_form_kwargs(self):
        kwargs = super(UpdateTeacherView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        return reverse('secretariat:list_teacher')


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    template_name = 'partial/delete.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Teacher, id=self.kwargs.get('id', 0))

    def get_success_url(self):
        return reverse('secretariat:list_teacher')


class ListGradeYearView(LoginRequiredMixin, ListView):
    template_name = 'grade_year/list.html'
    context_object_name = 'grade_years'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ListGradeYearView, self).get_context_data(**kwargs)
        context['total_count'] = len(context['grade_years'])
        return context

    def get_queryset(self):
        faculty = self.request.user.faculty.faculty
        return GradeYear.objects.select_related('department').filter(department__faculty_id=faculty.id)

timetable_v3/secretariat/templates/secretariat-base.html
{% load static %}
{% load custom_tags %}
<html>
    <head>
        <meta charset="UTF-8">
        <title>Dersplan Sistemi 3.0</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
  crossorigin="anonymous"></script>

        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="icon" type="image/x-icon" href="/favicon.ico">
    </head>
    <style>
        .table-responsive {
    margin: 30px 0;
}
.table-wrapper {
	background: #fff;
	padding: 20px 25px;
	border-radius: 3px;
	min-width: 1000px;
	box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.table-title {
	padding-bottom: 15px;
	background: #343a40!important;
	color: #fff;
	padding: 16px 30px;
	min-width: 100%;
	margin: -20px -25px 10px;
	border-radius: 3px 3px 0 0;
}
.table-title h2 {
	margin: 5px 0 0;
	font-size: 24px;
}
.table-title .btn-group {
	float: right;
}
.table-title .btn {
	color: #fff;
	float: right;
	font-size: 13px;
	border: none;
	min-width: 50px;
	border-radius: 2px;
	border: none;
	outline: none !important;
	margin-left: 10px;
}
.table-title .btn i {
	float: left;
	font-size: 21px;
	margin-right: 5px;
}
.table-title .btn span {
	float: left;
	margin-top: 2px;
}
table.table tr th, table.table tr td {
	border-color: #e9e9e9;
	padding: 12px 15px;
	vertical-align: middle;
}
table.table tr th:first-child {
	width: 60px;
}
table.table tr th:last-child {
	width: 100px;
}
table.table-striped tbody tr:nth-of-type(odd) {
	background-color: #fcfcfc;
}
table.table-striped.table-hover tbody tr:hover {
	background: #f5f5f5;
}
table.table th i {
	font-size: 13px;
	margin: 0 5px;
	cursor: pointer;
}
table.table td:last-child i {
	opacity: 0.9;
	font-size: 22px;
	margin: 0 5px;
}
table.table td a {
	font-weight: bold;
	color: #566787;
	display: inline-block;
	text-decoration: none;
	outline: none !important;
}
table.table td a:hover {
	color: #2196F3;
}
table.table td a.edit {
	color: #FFC107;
}
table.table td a.delete {
	color: #F44336;
}
table.table td i {
	font-size: 19px;
}
table.table .avatar {
	border-radius: 50%;
	vertical-align: middle;
	margin-right: 10px;
}
.highlight { background-color: #BFFBFF /*best friends forever x2! */ }
.danger { background-color: orangered;: #BFFBFF /*best friends forever x2! */ }
    </style>
<body>
{% include 'secretariat-header.html' %}
{% block content %}
{% endblock content %}
<script src="http://timetable.manas.edu.kg/js/ff33110.js"></script>

</body>
</html>

timetable_v3/secretariat/templates/secretariat-header.html
{% load static %}
<div class="jumbotron text-center" style="margin-bottom:0">
    <h1>Ders Planı Sistemi <span>3.0</span></h1>
    <p>Kırgızistan Türkiye Manas Üniversitesi</p>
</div>


    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <!-- Brand -->
        <a class="navbar-brand" href="">Kullanım Kılavuzu</a>

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'secretariat:class_room_timetable' %}">  DersPlanı Editörü </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'secretariat:list_class_room' %}">Fakülteye Ait Derslikler</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'secretariat:list_course' %}">Bölüm Dersleri</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'secretariat:list_grade_year' %}">Sınıflar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'secretariat:list_teacher' %}">Öğretmenler</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'secretariat:list_course_vs_room' %}"> Özel Alan Dersleri</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'secretariat:list_unused_course' %}"> DersPlana Yerleşmeyen Dersler Listesi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/"> DersPlan </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/profile/change-password">Şifre Değiştir</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'secretariat:logout' %}">Çıkış Yap</a>
                </li>

            </ul>
            {% endif %}
        </div>
    </nav>